### ISSUE TITLE
Disable !bookTickers stream 

### ISSUE THREAD

**Issue by aalwayslucky** [gmtech-xyz/safe-cex#14]
Is it possible to disable bookticker stream or throttle it so will get less often data ? it's getting 3-10mbps on avg it's too much. I was trying to modify code but couldn't figured out.

**Comment by iam4x** [comment]
Unfortunately data is pushed by exchanges as it moves, can't have control on that.
If you need the orderBook you can disable it or not subscribe to it at all.
