### ISSUE TITLE
incorrect unified margin calculation on binance + fix

### ISSUE THREAD

**Issue by rayanatrades** [gmtech-xyz/safe-cex#16]
Hi, e. g. considering we have ETH + USDT balance:

```
    {
        "accountAlias": "FzsRXqXqSgoCfWSg",
        "asset": "ETH",
        "balance": "1.21964998",
        "crossWalletBalance": "1.21964998",
        "crossUnPnl": "0.00000000",
        "availableBalance": "1.25752019",
        "maxWithdrawAmount": "1.21964998",
        "marginAvailable": true,
        "updateTime": 1706132869319
    },
    {
        "accountAlias": "FzsRXqXqSgoCfWSg",
        "asset": "USDT",
        "balance": "390.25635408",
        "crossWalletBalance": "390.25635408",
        "crossUnPnl": "6.14934583",
        "availableBalance": "2910.76417728",
        "maxWithdrawAmount": "390.25635408",
        "marginAvailable": true,
        "updateTime": 1706127056721
    }
```

Tuleep only picks USDT right now for margin calculation which would show negative `used` balance since it's `margin.availableBalance - margin.balance` (-2500 in case of example).

In order to fix this, we need to loop over other available assets and increase `total + used` by the value of each asset, e. g. taking ETH, we'd bump used by balance * price of ETH = 1.21964998 * 2400 which would make calculation correct.

Before
```
total | 390.26 USD
free | 2938.65 USD
upnl | 21.52 USD
used | -2548.39 USD
```

After
```
total | 3090.48 USD
free | 2936.10 USD
upnl | 19.82 USD
used | 154.38 USD
```

This is my proposed patch:
https://github.com/Tealstreet/safe-cex/commit/0da55bb3d268adf02fb51f7560946e01973363f3

**Comment by iam4x** [comment]
Thank's for the quick chat on Discord, fixed into https://github.com/gmtech-xyz/safe-cex/commit/44556654a592d667269c08f10fbab216a8466413
