### ISSUE TITLE
Add startTime/EndTime to fetchOHLCV() as optional parameters

### ISSUE THREAD

**Issue by lleewwiiss** [gmtech-xyz/safe-cex#2]
Both Binance and ByBit support specifying timestamps to timebox OHLCV data, it would be useful to also be able to do this through safe-cex for fetching historical data.

Happy to attempt to implement this for you

**Comment by iam4x** [comment]
Hey, yes, you can do a PR integrating those options.
I would just ask to make them optional, so it doesn't break the current implementation with defaults.
